enum ActionTypes {
    CREATE_COURSE = 'CREATE_COURSE',
    LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS',
    DELETE_COURSE_AT_INDEX = 'DELETE_COURSE_AT_INDEX',
    LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS',
}

export default ActionTypes;
